### ISSUE TITLE
adjust code to monocular recording

### ISSUE THREAD

**Issue by renderann** [dmirman/gazer#1]
Hi, 

I was wondering if it possible to adjust the code to monocular recording? so far, I exchanged the average_in_blink and average_in_pupil with right_in_blink and right_in_pupil but its causing trouble when I am trying to run the code for the baseline corrections (cause its still based on avg_pupil?).
Do you have any recommendation how to preceed? 
Thanks and all the best, 

Anna

**Comment by jgeller112** [comment]
Hello, 

In order for gazer to work correctly you have to have the correct column names.  The right_in_blink and right_in_pupil should have been changed to blink and pupil when reading in the files using the `merge_gazer_files` function. Did you do this?

**Comment by jgeller112** [comment]
Can you include some code snippets or what some of your output looks like for me?

**Comment by jgeller112** [comment]
It should not matter if you recorded mono or bi for tracking.

**Comment by renderann** [comment]
![grafik](https://user-images.githubusercontent.com/43436263/73775859-97546a80-47eb-11ea-9a07-1edf59dd427c.png)

**Comment by renderann** [comment]
####GAZER#####

install.packages("remotes")
remotes::install_github("dmirman/gazer")


install.packages("remotes")
install.packages("gazer")
install.packages("tidyverse")
install.packages("zoo")
install.packages("rlang")


library(remotes)
library(gazer)
library(tidyverse)
library(zoo)
library(knitr)

col_names <- c("subject","trial","blink","pupil", "x", "y", "time","message")
knitr::kable(col_names, col.names = "Names")


#merging all files
setwd("C:/Users/ANNA/Desktop/pilots with physio/pupildata/input/gaze")
file_list <- list.files(path = 'C:/Users/ANNA/Desktop/pilots with physio/pupildata/input/gaze', pattern = ".txt") 
pupil_files <- merge_pupil(
  file_list, 
  blink_colname = "RIGHT_IN_BLINK", 
  pupil_colname = "RIGHT_PUPIL_SIZE"
) 

#Deblinks
pup_extend<- pupil_files %>% 
  group_by(subject, trial) %>% 
  mutate(extendpupil=extend_blinks(pupil, fillback=100, fillforward=100, hz=250))

#Interpolation
pup_interp <- interpolate_pupil(
  pup_extend, 
  extendblinks = TRUE, 
  type = "linear")

#smoothing
rolling_mean_pupil_average <- as.data.frame(pup_interp) %>% 
  select(
    subject, trial, pupil, extendpupil,interp,
    time, interp, sample_message, trial_start_time, timestamp, half, block, rep, source, judgment
  ) %>%
    mutate(movingavgpup = moving_average_pupil(interp, n = 5))

#baseline correction

baseline_pupil <- baseline_correction_pupil(
  rolling_mean_pupil_average,  pupil_colname = "movingavgpup", 
  baseline_window = c(500, 1000), 
  baseline_method = 'sub'
)

#Rescaling
timebinsmm <- rolling_mean_pupil_average  %>% 
  mutate(pupilmm = (movingavgpup * 5)/5570.29)

#artefacts
pup_missing <- count_missing_pupil (baseline_pupil, missingthresh = .2)

puphist <- ggplot(pup_extend, aes(x = extendpupil)) + 
  geom_histogram(aes(y = ..count..), colour = "green", binwidth = 0.5)  + 
  geom_vline(xintercept = 2500, linetype="dotted") +
  geom_vline(xintercept = 5100, linetype="dotted") + 
  xlab("Pupil Size") + 
  ylab("Count") + 
  theme_bw()

print(puphist)

pup_outliers <- pup_missing %>% 
  dplyr::filter(interp  >= 2500, interp <= 5100)

**Comment by jgeller112** [comment]
Where is the error occurring? It seems like you are using older version of the package. In the newest version (read paper here:https://psyarxiv.com/4qwr8/ ) we use the merge_gazer_files function and combine the interpolation and smoothing function. 

The data file you show seems to have the correct column names. I am not exactly sure what is going on with the baselining. Maybe you can share a your data with me?

**Comment by jgeller112** [comment]
```
merge_gazer_files <- function (file_list, blink_colname="blink", pupil_colname="pupil", filetype="sr") {  
  #file list is path to .xls files
  library(data.table)

  if (filetype=="sr") {
    
  dataset <- do.call("rbind", lapply(file_list, FUN=function(files){
    
    for (i in 1:length(files)){ 
      if(file.exists(files[i])){
        message( "now processing:", files[i])
      }
    }
  
    fread(files, header=TRUE, sep="\t", na.strings = ".", fill=TRUE)})) #fread makes reading in files quick
  
    change_name <- select(dataset,subject=RECORDING_SESSION_LABEL, trial =  TRIAL_INDEX,    blink = blink_colname, pupil = pupil_colname, message= "SAMPLE_MESSAGE",  everything())
  
    names(change_name) <- tolower(names(change_name))
  
    change_name$time <- change_name$timestamp-change_name$ip_start_time
  
    return(as_tibble(change_name))
  }
  
if (filetype=="edf") { 
  
  dataset <- do.call("rbind", lapply(file_list, FUN=function(files){
    
    for (i in 1:length(files)){ 
      if(file.exists(files[i])){
        message( "now processing:", files[i])
      }
    }
    
    fread(files, header=TRUE, na.strings = "NA", fill=TRUE)})) #fread makes reading in files quicke

   return(as_tibble(dataset))
  }

}
```

**Comment by jgeller112** [comment]
just FYI the pupil_avg is just a variable I use in-script. It does not reflect bi or mono recording. The pupil colname you provided in the functions get renamed to that.

**Comment by renderann** [comment]
I took a look at the new version as well but its I think the edf reading function is only for linux and mac and not for windows, isnt it? 
Yeah of course, that would be great, thanks, its just pilot data at this point... I wanted to make sure the dataset is correct before we actually start running participants.
The error occurs when: Calculating median baseline from:500-1000

> #baseline correction
> 
> baseline_pupil <- baseline_correction_pupil(
+   rolling_mean_pupil_average,  pupil_colname = "movingavgpup", 
+   baseline_window = c(500, 1000), 
+   baseline_method = 'sub'
+ )
Calculating median baseline from:500-1000
c("14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", 
"14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", 
"14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", 
"14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", 
"14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", 
"14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", 
"14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", 
"14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", 
"14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", 
"14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", 
"14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", 
"14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", 
"14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "14_DarkAgency_2020-01-31-1322", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", 
"900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", 
"900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", 
"900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgency_2020-01-31-1009", "900_DarkAgeError in dplyr::full_join(., datafile) : object '.' not found


https://www.dropbox.com/sh/8o75k2lwgr6bjvq/AABJrEvig1N6s9INjHS27jY-a?dl=0

**Comment by renderann** [comment]
thanks very much for replying so quickly and taking a look at the data!

**Comment by jgeller112** [comment]
It is for Windows as well! You need to download the SR toolbox from them.

**Comment by renderann** [comment]
I downloaded the toolkit from the website in your manuscript
https://www.sr-support.com/forumdisplay.php?17-EyeLink-Display-Software
but I couldnt install ‘edfR’ package (Hubbard, 2014) that you mentioned, on his github homepage (https://github.com/jashubbard/edfR) it says 
'Currently works with Mac or Linux only. Windows support coming soon.'
So I thought that might have been the problem

**Comment by jgeller112** [comment]
I did not know about that! 


I fixed the issue. I used a full_join after ungroup which is why it threw that error. if you update the package you should be able to baseline your data. 

Thank you for trying it out and messaging me!

**Comment by renderann** [comment]
Oh cool, thanks so much, thats great!! I'll try and let you know!

**Comment by jgeller112** [comment]
> I downloaded the toolkit from the website in your manuscript
> https://www.sr-support.com/forumdisplay.php?17-EyeLink-Display-Software
> but I couldnt install ‘edfR’ package (Hubbard, 2014) that you mentioned, on his github homepage (https://github.com/jashubbard/edfR) it says
> 'Currently works with Mac or Linux only. Windows support coming soon.'
> So I thought that might have been the problem

What Rstudio version are you using? I was certain that as long as you used older version of Rstudio you could get edfR to work.

**Comment by renderann** [comment]
I have 3.6.1 and 3.6.2 (and switched to 3.6.1 for your older package), I didnt try to get edfR with older versions than 3.6.1, but thats a good idea actually, do you know which version would work?

**Comment by jgeller112** [comment]
> I have 3.6.1 and 3.6.2 (and switched to 3.6.1 for your older package), I didnt try to get edfR with older versions than 3.6.1, but thats a good idea actually, do you know which version would work?

follow this thread: https://github.com/jashubbard/edfR/issues/9

**Comment by renderann** [comment]
The baselinecorrection of the older code works well now thanks!
I'm still struggeling to install edfR, even using older Rstudio versions (1.1.463 and1.0.153) with RVersion 3.5.0, not sure what I'm doing wrong here, but as long as the older code works, thats all good..
Thanks!

**Comment by jgeller112** [comment]
For now, I would just read in the sample reports from SR and run the pipeline that way. It is a bummer about the Windows thing--it used to work!

**Comment by renderann** [comment]
thanks anyway or trying! Yeah, sample reports work :)

**Comment by renderann** [comment]
Heya, 
I have another question about the order of preprocessing the pupildata. I was wondering why the artefact rejecting is not done after deblinking and before interpolating?
All the best, 
Anna

**Comment by jgeller112** [comment]
Given the aggregation does not happen until the end, it does not really matter when it is done.  One of the main reasons we decided to do it at end is that throwing out data right away might cause trouble for baselining (messages might be thrown out).

**Comment by renderann** [comment]
Ah alright, thanks!
I was also wondering if it possible to select several sample_message events at once in the while doing the event time alignement?
Or would you recommend to do it in different datasets and merge them in the end?
In this part:
baseline_pupil_Clockonset <- baseline_pupil %>% 
  group_by(subject, trial) %>%  
  mutate(
    time_zero = onset_pupil (time, sample_message, event = c("ClockOnset"))
  ) %>%
  ungroup() %>% 
  filter(time_zero >= 0, time_zero <= 3000) %>%
  select(
    subject, trial, time, time_zero, 
    sample_message, baselinecorrectedp, interp, baseline, time, half, script, rep, source, judgment
  )

Thanks again for your help!

**Comment by jgeller112** [comment]
You can only align the time course to one event. I would not merge them. I would just create separate tibbles/DFs and plot them.  Is there a reason why you want to realign the data to multiple events?

**Comment by renderann** [comment]
alright, yeah thats a good idea! 
We have a mixed design, pre measurement (within), watching one of three different movies (between factor) and then post measurement (within), so we need trialonset as well as movieonset, but thats not complicated to do... Thanks!

**Comment by jgeller112** [comment]
Hopefully gazer has been fairly painless to use! Please let me know if you any more questions!

I am going to look into the windows EDF issue for you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by renderann** [comment]
Thanks so much! It's a great code, I'm soo pleased I can use it, thanks for sharing it!  
I just cannot yet get my head around why it doesnt matter if artefact rejection is done after interpolation cause then the data within blinks is already replaced by the values of interpolation and then it doesnt really pick up on the blinks anymore or am I misunderstanding and it does still do that?

**Comment by jgeller112** [comment]
Blinks are preserved in the data and contained in the blink column. The Missing data function uses this blink column to calculate excessive data loss and removes that. Does that make sense?


On Feb 4, 2020, at 10:52 PM, renderann <notifications@github.com> wrote:

﻿

Thanks so much! It's a great code, I'm soo pleased I can use it, thanks for sharing it!
I just cannot yet get my head around why it doesnt matter if artefact rejection is done after interpolation cause then the data within blinks is already replaced by the values of interpolation and then it doesnt really pick up on the blinks anymore or am I misunderstanding and it does still do that?

**Comment by renderann** [comment]
Ahh okay, yeah that does make sense, I didnt realize that this function uses the blink column still! Thanks again!
