### ISSUE TITLE
unable to use edfR

### ISSUE THREAD

**Issue by ufangYang** [dmirman/gazer#12]
I wonder is there anyone having a similar problem as me that _edfR_ does not work (had reported an issue in edfR: https://github.com/jashubbard/edfR/issues/12).  Is there any other alternative approach to parse the _edf_ file when package _edfR_ doesn't work? thanks a lot!

**Comment by jgeller112** [comment]
Hello, 

Yeah this is common issue with edfR. Luckily I have gazeR in a container on Code Ocean that also includes edfR. Here is a link showing how to use the gazeR package with Code Ocean: https://www.youtube.com/watch?v=5IQmP9Yrh1k.

**Comment by jgeller112** [comment]
Can you please post the code you used when you got the error?

**Comment by ufangYang** [comment]
Hi, here is the error message for parsing the data on Code Ocean

Error: Can't subset columns that don't exist. x The column blinkdoesn't exist. Runrlang::last_error()to see where the error occurred.

any suggestion to add this column before parsing? Thanks a lot

**Comment by jgeller112** [comment]
Please see my comment above. I need the code chunks you ran to diagnose the problem.

**Comment by ufangYang** [comment]
Hi, I use this line of code to load *.edf file,
gazer:: parse_edf(file.choose(), output_dir = '/root/capsule/code')

**Comment by jgeller112** [comment]
Can you share your EDF file with me? I cant replicate this problem, so it might be due to the file you are using.

**Comment by jgeller112** [comment]
Also, are you using this for pupil or gaze experiment?

**Comment by ufangYang** [comment]
> Also, are you using this for pupil or gaze experiment?

it was a gaze experiment, I can share the data with you via email/private message since it is unpublished data, thank you.  I wonder how heavy the dependency of using `gazer::parse_edf()` on Code Ocean.  Because I ran out of the quote already on CO for further testing (1hr per month).

**Comment by jgeller112** [comment]
gazer:: parse_edf(file.choose(), output_dir = '/root/capsule/code', type="gaze")

The default is pupil. 


I would check out this: https://psyarxiv.com/gvcxb/. You should be able to use Data Viewer and extract the data.

**Comment by jgeller112** [comment]
If you sign-up you should get 10 hours a month.

**Comment by ufangYang** [comment]
hi @jgeller112 I tried parsing the edf files with new eye-tracking data; this time it seemed to have parsed the data, but the process did not complete due to one file. I'm not sure why I got a different error because all of the files had the same structure. Below is the error (I masked the name of the file). Here I shared the codeocean with you, it might be easier to debug, let me know if you cannot access it. thanks a bunch! 

`Done processing all files!
Error in samps_all[[1]] : subscript out of bounds
In addition: Warning message:
Problem with file XXX.edf ` #(specific file name)

https://codeocean.com/capsule/9187727/tree

**Comment by jgeller112** [comment]
Can you send me the EDF that is causing the issue?

**Comment by ufangYang** [comment]
sure, which email should I send to you?

**Comment by jgeller112** [comment]
drjasongeller@gmail.com
