### ISSUE TITLE
sample_message to message not updated in merge_pupil

### ISSUE THREAD

**Issue by bzuck-temple** [dmirman/gazer#16]
Hi there! 

I am updating some past scripts and noticed that `merge_pupil` does not change sample_message to message but `merge_gazer_files` does. This becomes an issues when you call `baseline_correction_pupil_msg`. Is merge_pupil just an old hold over from the earlier versions of the package?  Everything is working with the updated calls.

Thanks,
Bonnie

**Comment by jgeller112** [comment]
Hi Bonnie,

Merge_pupil is an old hold over--I should probably delete it...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Bonnie Zuckerman ***@***.***>
Sent: Wednesday, March 24, 2021 9:44:59 AM
To: dmirman/gazer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [External] [dmirman/gazer] sample_message to message not updated in merge_pupil (#16)


Hi there!

I am updating some past scripts and noticed that merge_pupil does not change sample_message to message but merge_gazer_files does. This becomes an issues when you call baseline_correction_pupil_msg. Is merge_pupil just an old hold over from the earlier versions of the package? Everything is working with the updated calls.

Thanks,
Bonnie
