### ISSUE TITLE
unable to install saccades and edfR

### ISSUE THREAD

**Issue by NatKar2021** [dmirman/gazer#17]
Hi, 

I am unable to install packages saccades and edfR. The message I receive is:

"Error: (converted from warning) package 'zoom' was built under R version 4.0.4
Execution halted
ERROR: lazy loading failed for package 'saccades'
* removing 'C:/Users/.../Dokumenter/R/win-library/4.0/saccades'
Error: Failed to install 'saccades' from GitHub:
  (converted from warning) installation of package ‘C:/Users/.../AppData/Local/Temp/Rtmp6TEECc/file696864227a8f/saccades_0.2-1.tar.gz’ had non-zero exit status"

Maybe you have seen this before? Any help is very appreciated.

**Comment by jgeller112** [comment]
Please see this post: https://github.com/dmirman/gazer/issues/3

What OS are you using? did you try:

``
library("remotes")
install_github("tmalsburg/saccades/saccades", dependencies=TRUE)
```

**Comment by NatKar2021** [comment]
Dear Dan, 
Thanks for your prompt answer. I use Windows 10. 
I tried to use dependencies=TRUE and the issue persist.
From the post #3 it seems that the best option is to move the analyses to the CO or to export data directly from data viewer and process it using the the gazeR manuscript that doesn’t rely on edfR. It looks like this version does not use "saccades". I will try these solutions and will let you know how it worked.

**Comment by NatKar2021** [comment]
Hi again! 
I tried to run the analyses in CO, but get the wrong message (similar to the one in #3): 
Error: Can't subset columns that don't exist.
x The column `blink` doesn't exist.
Run `rlang::last_error()` to see where the error occurred. 

When I run rlang::last_eroor()
> rlang::last_error()
<error/vctrs_error_subscript_oob>
Can't subset columns that don't exist.
x The column `blink` doesn't exist.
Backtrace:
  1. gazer::parse_edf(file.choose(), output_dir = output_dir)
 29. vctrs:::stop_subscript_oob(...)
 30. vctrs:::stop_subscript(...)
Run `rlang::last_trace()` to see the full context.

How should I proceed? I do not have mac (I saw that the user in #3 switched to mac after this error). 
Thanks in advance for your help!

**Comment by jgeller112** [comment]
Can you please provide me with file you are using?

**Comment by NatKar2021** [comment]
Yes. It is here https://drive.google.com/file/d/1O8zZy8iSBh1fCRNGQLARnqVX9SjGAZGz/view?usp=sharing
thanks in advance.

**Comment by jgeller112** [comment]
Huh...I cannot download the file. It says it is in owner's trash. Can you send it to me another way? Perhaps through email?

**Comment by NatKar2021** [comment]
Oh, I am sorry, I accidentally removed the folder. Here is a link again, it should work now https://drive.google.com/file/d/1O8zZy8iSBh1fCRNGQLARnqVX9SjGAZGz/view?usp=sharing

**Comment by jgeller112** [comment]
I had no problems running your EDF file through the Code Ocean GazeR container (https://drive.google.com/file/d/1EgMm7nmLQDyPOiM9z8ugLX8dgpCX4Vn-/view?usp=sharing). Did you watch the video I posted showing how to read in files through Code Ocean?

To better diagnose the problem, can you please copy and paste the code you used in the Code Ocean container?

Jason

**Comment by NatKar2021** [comment]
Hi. Thank you so much for trying. I did follow the video. 
Here is the code that I used in the CO container: 

library(data.table)
library(tidyverse)
library(zoo)
library(here)

devtools::load_all()

library(gazer)

# get the whereabouts
here()

# define output path
output_dir = '/root/capsule/code'

# parse edf 
gazer::parse_edf(file.choose(), output_dir = output_dir) 

After that I select the file, I receive the above-reported error. Shall I try with csv files, directly reported from Data Viewer, in R?

**Comment by jgeller112** [comment]
I think getting files from Data Viewer will be the easiest solution.

On Apr 3, 2021, at 4:06 PM, NatKar2021 ***@***.***> wrote:

﻿

Hi. Thank you so much for trying. I did follow the video.
Here is the code that I used in the CO container:

library(data.table)
library(tidyverse)
library(zoo)
library(here)

devtools::load_all()

library(gazer)

get the whereabouts

here()

define output path

output_dir = '/root/capsule/code'

parse edf

gazer::parse_edf(file.choose(), output_dir = output_dir)

After that I select the file, I receive the above-reported error. Shall I try with csv files, directly reported from Data Viewer, in R?

**Comment by jgeller112** [comment]
You need to set the working directory to where the EDF file is.

As a side note, what kind of paradigm is this data from?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: NatKar2021 ***@***.***>
Sent: Saturday, April 3, 2021 4:06:00 PM
To: dmirman/gazer ***@***.***>
Cc: Geller, Jason ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [dmirman/gazer] unable to install saccades and edfR (#17)


Hi. Thank you so much for trying. I did follow the video.
Here is the code that I used in the CO container:

library(data.table)
library(tidyverse)
library(zoo)
library(here)

devtools::load_all()

library(gazer)

get the whereabouts

here()

define output path

output_dir = '/root/capsule/code'

parse edf

gazer::parse_edf(file.choose(), output_dir = output_dir)

After that I select the file, I receive the above-reported error. Shall I try with csv files, directly reported from Data Viewer, in R?

**Comment by NatKar2021** [comment]
Thank you for your help. Unfortunately, setting the working directory to where the EDF file is did not work. 
The paradigm is Looking while Listening, used in infant research to examine preference for different audio stimuli. 
I will try to work with an csv file in R then. Best and thanks again for your assistance! Best.

**Comment by jgeller112** [comment]
Following these exact steps in Code Ocean should work. 
```
library(tidyverse)
library(data.table)
library(tidyverse)
library(zoo)
library(here)

devtools::load_all()
```

```

setwd("~/capsule/data") # your data should be placed in data. 
edf.directory= "~/capsule/data" # path to data
csv.directory=here() # path where new files should be stored
file_list <- list.files (path=edf.directory, pattern=".edf") # extract the edfs from path

```

```
parse_edf(file_list, output_dir=csv.directory, type="vwp") # the default is pupil and you do not want that


```

**Comment by jgeller112** [comment]
If you have access to Data Viewer, reading the csv files into gazeR is preferred. 

Here is an early paper draft showing you how to use gazeR with the csv files: https://psyarxiv.com/gvcxb/

**Comment by NatKar2021** [comment]
Hi Jason, 

I am sorry for my radio silence. 
Thank you so much for this solution in Code Ocean. It did work this time!! 
Next time I will try with the csv files directly. 

Thanks again for all your help!
