### ISSUE TITLE
Baseline correction problem

### ISSUE THREAD

**Issue by paradeisios** [dmirman/gazer#18]
I have done all the preprocessing steps, as specified in the paper
But when i try to perform baseline corrections,my output is :
Error: Problem with `filter()` input `..1`. x comparison (1) is possible only for atomic and list types i Input `..1` is `message == "target"`. i The error occurred in group 1: subject = 1, trial = "1". Run `rlang::last_error()` to see where the error occurred.

This is the commend I use:
  baseline_pupil <- baseline_correction_pupil_msg(smooth_interp,
                                                   pupil_colname = "pup_interp",
                                                   baseline_dur = 50,
                                                    event="target",
                                                    baseline_method = "sub")

**Comment by jgeller112** [comment]
Hi! 

I need to have more information. Can you share the data you are working with—maybe one subject?

**Comment by paradeisios** [comment]
The code i use is :
baseline_pupil <- baseline_correction_pupil_msg(datafile=smooth_interp, 
                                                                               pupil_colname='pup_interp',                                                                                  
                                                                               baseline_dur = 100,                                                                                             
                                                                              baseline_method ="sub",
                                                                              event = "GLOBAL")
Ι want to baseline correct for the first 100 ms for the start of each trial.
[test.txt](https://github.com/dmirman/gazer/files/6546323/test.txt)

**Comment by jgeller112** [comment]
Looking at the txt file you provided it appears you do not have a message column denoting when certain events happened in each trial. You need to have this column when using `baseline_correction_pupil_msg`. 

As an alternative, you can use the `baseline_correction _pupil` function that takes a user-specified time range as the baseline. 

```
pdc <- baseline_correction_pupil(datafile, pupil_colname="pupil", baseline_window=c(0, 150), baseline_method="sub")

```

**Comment by jgeller112** [comment]
Please let me know  @paradeisios if this answers your question/solves your problem so I can close this issue.

**Comment by paradeisios** [comment]
yes, you can close it. thank you
