### ISSUE TITLE
Read pupil data from excel

### ISSUE THREAD

**Issue by hanyf-psych** [dmirman/gazer#20]
Hi,

I was wondering if it could directly read pupil size data in the excel file. I recorded the pupil size data using MATLAB, and exported the data as excel file. But when I used the merge_gazer_files function, it reported an error. I have tried several methods, but I still can't solve it. The column "RECORDING_SESSION_LABEL" exist in the excel file. When I tried to use another function (read_fixation_report), it reported the same error.

![image](https://user-images.githubusercontent.com/61484703/131506502-573c8871-c2d1-4133-8194-1da689c2b543.png)
![image](https://user-images.githubusercontent.com/61484703/131506719-903b71b1-5589-47ee-84af-b1fed67d9caf.png)

![image](https://user-images.githubusercontent.com/61484703/131507126-1142ad0d-8a18-4f67-a69d-01cbb970eb13.png)
![image](https://user-images.githubusercontent.com/61484703/131507964-351eab9f-7422-4682-8b96-f260554dd066.png)

**Comment by jgeller112** [comment]
Hi, 

gazeR requires specific column names. You can use the `make_gazer` function to change the column names to match the naming conventions used by gazeR. 

```
new_df <- make_gazer(data, subject="RECORDING_SESSION_LABEL", trial="TRIAL_INDEX", time="time", x="PUPIL_X", y="PUPIL_Y", pupil=PUPIL_SIZE)
```
Alternatively, you can just change these columns in the Excel spreadsheet.

**Comment by hanyf-psych** [comment]
Ok, thanks a lot for your help.

> Hi,
> 
> gazeR requires specific column names. You can use the `make_gazer` function to change the column names to match the naming conventions used by gazeR.
> 
> ```
> new_df <- make_gazer(data, subject="RECORDING_SESSION_LABEL", trial="TRIAL_INDEX", time="time", x="PUPIL_X", y="PUPIL_Y", pupil=PUPIL_SIZE)
> ```
> 
> Alternatively, you can just change these columns in the Excel spreadsheet.

**Comment by hanyf-psych** [comment]
Hi,

I met another problem when using the `make_gazer` function and the `baseline_correction_pupil_msg` function. I'd like to know how to add a column to decribe the stimulus onset message. Thanks a lot.
![image](https://user-images.githubusercontent.com/61484703/131761567-75bddd9c-82f8-4360-b0c5-02eb0ff0fe5d.png)
![image](https://user-images.githubusercontent.com/61484703/131761695-0d2ac27a-9bc1-4c42-b63f-461fd9160072.png)

**Comment by jgeller112** [comment]
The message column is something you would get from SR Data Viewer or from the EDF files themselves. 

If you know the relative onset of events and know what your baseline period is then you can use the `baseline_correlation_pupil` function and indicate a baseline_window (eg., 500,1000) which would take the median ps between 500 ms and 1000 ms.

**Comment by jgeller112** [comment]
An earlier version of my paper (attached)  covers what you would without the message column.  

[GazeR_final (2).pdf](https://github.com/dmirman/gazer/files/7095166/GazeR_final.2.pdf)

**Comment by hanyf-psych** [comment]
Hi, thanks a lot, I have solved the problem by changing the column "EVENT" in the excel into "message".

**Comment by jgeller112** [comment]
I am going to close the issue but feel free to reopen it if you have other issues.
