### ISSUE TITLE
Error when running dplyr::gather

### ISSUE THREAD

**Issue by Naylasokhn** [dmirman/gazer#21]
Dear all,

I am trying to run the Gazer_walkthrough.R script, i am getting an error when running the following part 

`gaze_obj <-gaze_aoi %>%
  dplyr::gather(key ="object", value ="fix",Targ, Comp, Unrelated, factor_key =TRUE) %>%
  dplyr::mutate(Fix =replace_na(fix, FALSE)) # recode NA as not-
`
Error: 'gather' is not an exported object from 'namespace:dplyr'

Any help is much appreciated
Thanks in advance!
Best regards,
Nayla

**Comment by jgeller112** [comment]
Hi @Naylasokhn, 

Thanks for reporting this! Indeed gather is not part of the dplyr library, it is a tidyr function.You change the dplyr:: part to tidyr::. Another issue is that gather function is being depreciated. I will update that to use pivot_longer in the future. 

Jason

**Comment by Naylasokhn** [comment]
Dear Jason,

Thanks a lot! this works fine now :D
Best,
Nayla
