### ISSUE TITLE
Accommodating data timebinned in Eyelink

### ISSUE THREAD

**Issue by emilie-brotherhood** [dmirman/gazer#26]
Hi,

Thanks for the comprehensive overview of the package, much appreciated!

One quick question - when the functions specify hz input, is this referring to the original sampling rate, or to the downsampled rate if this has already been conducted in Eyelink dataviewer?

**Comment by jgeller112** [comment]
You would input whatever hz your data are currently sampled at. So, if I binned to 100 Hz  when exporting from Data Viewer I would input 100 Hz.

**Comment by emilie-brotherhood** [comment]
Fab thanks for coming back so quickly
